game/urls.py
from django.urls import path
from . import views

app_name = "game"

urlpatterns = [
    path('rsp/', views.rsp, name="rsp"),
    path('rsp/<str:pick>', views.result, name="result"),
    path('reset/', views.reset, name="reset"),
    path('create-weapon/', views.create_weapon, name="create_weapon"),
    path('list-weapon/', views.list_weapon, name="list_weapon"),
]

jgDjango/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('page/', include('page.urls')),
    path('game/', include('game.urls')),
]

page/urls.py
from django.urls import path
from . import views

app_name = "page"

urlpatterns = [
    path('', views.index, name="index"),
    path('create/', views.create, name="create"),
    path('read/', views.read, name="read"),
    path('<int:posting_id>/', views.detail, name="detail"),
    path('<int:posting_id>/update/', views.update, name="update"),
    path('<int:posting_id>/delete/', views.delete, name="delete"),
]

game/models.py
from django.db import models

# Create your models here.
# [미션] Weapon 모델을 Class로 생성.
# [미션] models.Model 클래스를 상속받음
# [미션] name : 문자열 필드, 최대 길이 20
# [미션] power : 정수형 필드
class Weapon(models.Model):
    name = models.CharField(max_length=20)
    power = models.IntegerField()

    def __str__(self):
        return self.name

page/models.py
from django.db import models

# Create your models here.
# Posting 모델 작성
class Posting(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    
    # [코드 작성] admin 페이지에서 Posting 객체들이 title로 보여지도록 코드 작성
    def __str__(self):
        return self.title

game/views.py
from django.shortcuts import render, redirect
from random import *
# [미션] models.py의 Weapon 모델 불러오기
from .models import Weapon

# Create your views here.
win = 0
draw = 0
lose = 0

def rsp(request):
    global win, draw, lose
    context = {
        "win": win,
        "draw": draw,
        "lose": lose,
    }
    return render(request, "game/rsp.html", context)

def result(request, pick):
    global win, draw, lose
    rsp = ["가위", "바위", "보"]
    com = choice(rsp)

    if pick == com:
        result = "무승부"
        draw += 1
    elif (pick == "가위" and com == "보") or (pick == "바위" and com == "가위") or (pick == "보" and com == "바위"):
        result = "승리"
        win += 1
    else :
        result = "패배"
        lose += 1

    context = {
        "pick": pick,
        "com": com,
        "result": result,
        "win": win,
        "draw": draw,
        "lose": lose,
    }
    return render(request, "game/result.html", context)

def reset(request):
    global win, draw, lose
    win, draw, lose = 0, 0, 0
    return redirect("game:rsp")

def create_weapon(request):
    if request.method == "POST":
        weapon_name = request.POST.get('weapon-name')
        weapon_power = request.POST.get('weapon-power')
        
        # [미션] Weapon 모델의 name과 content 필드값에 form으로 넘겨준 값을 저장하는 객체 생성
        # [미션] Weapon.objects.create를 사용하여 Weapon 객체 생성
        # [미션] Weapon의 name 필드에 weapon_name 변수 값 저장
        # [미션] Weapon의 power 필드에 weapon_power 변수 값 저장
        Weapon.objects.create(
            name = weapon_name,
            power = weapon_power,
        )
        return redirect('game:list_weapon')
    else:
        return render(request, 'game/create_weapon.html')

def list_weapon(request):
    # [미션] Weapon 모델의 모든 객체를 weapons 리스트로 가져오기
    weapons = Weapon.objects.all()

    context = {
        # [미션] weapons 리스트를 html에 넘겨주기
        # [미션] None을 지우고 작성
        'weapons': weapons,
    }

    return render(request, 'game/list_weapon.html', context)

page/views.py
from django.shortcuts import render, redirect
# [미션] models.py의 Posting 모델 불러오기
from .models import Posting

# Create your views here.
def index(request):
    return render(request, 'page/index.html')

def create(request):
    # 만약 form에서 값을 전송하는 방식이 'POST'일 경우
    if request.method == 'POST':
        # POST 방식으로 넘어온 값 중 'title'과 'content'의 값을 딕셔너리 형태로 반환
        posting_title = request.POST.get('title')
        posting_content = request.POST.get('content')

        # [미션] Posting 모델의 title과 content 필드값에 form으로 넘겨준 값을 저장하는 객체 생성
        Posting.objects.create(
            title=posting_title,
            content=posting_content,
        )
        # 앱 이름이 'page'인 urls.py에서 name 속성값이 'read'인 url로 리다이렉트
        return redirect('page:read')
    else:
        return render(request, 'page/create.html')

def read(request):
    # [미션] Posting 모델의 모든 객체를 리스트로 가져오기
    postings = Posting.objects.all()
    context = {
        # [미션] context를 이용하여 postings 리스트를 딕셔너리 형식으로 html에 넘겨주기
        # [미션] None을 지우고 작성
        'postings': postings,
    }
    return render(request, 'page/read.html', context)

def detail(request, posting_id):
    # [코드 작성] Posting 모델의 객체 중 id 값이 posting_id와 같은 객체를 가져옴
    posting = Posting.objects.get(id=posting_id)
    context = {
        # [코드 수정] posting 객체에 저장되어있는 값을 html에 넘겨주기
        # [코드 수정] None을 지우고 작성
        'posting': posting,
    }
    return render(request, 'page/detail.html', context)

def update(request, posting_id):
    # [코드 작성] Posting 모델의 객체 중 id 값이 posting_id와 같은 객체를 가져옴
    posting = Posting.objects.get(id=posting_id)

    # 만약 form에서 값을 전송하는 방식이 'POST'일 경우
    if request.method == 'POST':
        # [코드 작성] POST 방식으로 넘어온 값 중 'title'과 'content'의 값을 딕셔너리 형태로 반환
        posting_title = request.POST.get('title')
        posting_content = request.POST.get('content')

        # [코드 작성] posting 객체의 title과 content 필드값에 form으로 넘겨준 값을 각각 넣어줌
        posting.title = posting_title
        posting.content = posting_content

        # [코드 작성] posting 객체의 변경사항 저장
        posting.save()
        # 앱 이름이 'page'인 urls.py에서 name 속성값이 'detail'인 url로 리다이렉트
        return redirect('page:detail', posting_id)
    else:
        context = {
            # [코드 수정] posting 객체에 저장되어있는 값을 html에 넘겨주기
            # [코드 수정] None을 지우고 작성
            'posting': posting,
        }
        return render(request, 'page/update.html', context)

def delete(request, posting_id):
    # [코드 작성] Posting 모델의 객체 중 id 값이 posting_id와 같은 객체를 가져옴
    posting = Posting.objects.get(id=posting_id)
    # [코드 작성] posting 객체 삭제
    posting.delete()
    return redirect('page:read')

game/templates/game/create_weapon.html
{% extends 'base.html' %}

{% block head %}
  <style>
    .weapon {
      padding: 10px;
      margin: 10px;
    }
    input {
      font-family: 'GangwonEdu_OTFBoldA';
    }
    input[type=submit] {
      padding: 5px 10px;
      border: 1px solid;
      border-radius: 10px;
      background-color: Khaki;
      color: SaddleBrown;
      text-decoration: none;
      cursor: pointer;
    }
  </style>
{% endblock %}

{% block body %}
  <form action="" method="post">
    {% csrf_token %}
    <div class="weapon">
      <label for="weapon-name">무기 이름</label>
      <input name="weapon-name" id="weapon-name" type="text">
    </div>

    <div class="weapon">
      <label for="weapon-power">무기 공격력</label>
      <input name="weapon-power" id="weapon-power" type="number">
    </div>

    <div class="weapon">
      <input type="submit" value="무기 생성">
    </div>
  </form>
{% endblock %}

game/templates/game/list_weapon.html
{% extends 'base.html' %}

{% block head %}
  <style>
    
  </style>
{% endblock %}

{% block body %}
  <h1>전체 무기 목록</h1>
  <ul>
    {% for weapon in weapons %}
      <!-- [미션] weapon의 power도 화면에 출력되도록 만들기 -->
      <li><p>{{weapon.name}} (공격력: {{weapon.power}})</p></li>
    {% empty %}
      <li><p>무기가 없습니다.</p></li>
    {% endfor %}
  </ul>
{% endblock %}

game/templates/game/result.html
{% extends 'game/rsp.html' %}

{% block rsp %}
  <h1>가위바위보 게임 결과</h1>
  <p>나는 <b>{{pick}}</b>를 선택했습니다.</p>
  <p>컴퓨터는 <b>{{com}}</b>를 선택했습니다.</p>
  <h2 style="color: red;">
    {% if result == "승리" %}
      내가 이겼습니다.
    {% elif result == "무승부" %}
      비겼습니다.
    {% else %}
      컴퓨터가 이겼습니다.
    {% endif %}
  </h2>
{% endblock %}

game/templates/game/rsp.html
{% extends 'base.html' %}

{% block head %}
  <style>
    .rsp {
      display: flex;
      flex-wrap: wrap;
      padding: 10px 0;
    }
    .rsp a {
      margin: 0 2px;
      padding: 10px 20px;
      border: 1px solid;
      border-radius: 15px;
      text-decoration: none;
    }
    .rsp a:hover {
      background-color: rgb(225, 225, 255);
    }
    .count {
      width: 25%;
      padding: 10px;
      margin: 10px 0;
      border: 1px solid;
    }
  </style>
{% endblock %}

{% block body %}

  {% block rsp %}
    <h1>가위바위보 게임</h1>

  {% endblock %}
  <div class="count">
    <p>승리 횟수 : {{win}}회</p>
    <p>무승부 횟수 : {{draw}}회</p>
    <p>패배 횟수 : {{lose}}회</p>

    <a href="{% url 'game:reset' %}">초기화</a>
  </div>

  <h3>선택해주세요~</h3>
  <div class="rsp">
    <a href="{% url 'game:result' '가위' %}">가위</a>
    <a href="{% url 'game:result' '바위' %}">바위</a>
    <a href="{% url 'game:result' '보' %}">보</a>
  </div>
  
{% endblock %}

jgDjango/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>jgDjango</title>
  <link rel="icon" href="{% static 'images/favicon-96x96.png' %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/base.css' %}">
  {% block head %}
  {% endblock %}
</head>
<body>
  <div class="navbar">
    <span>
      <a href="{% url 'page:index' %}">
        <img class="logo" src="{% static 'images/jgcat.jpg' %}" alt="jgcat">
      </a>
    </span>
    <span>
      <a href="{% url 'page:read' %}">글목록</a>
    </span>
    <span>
      <a href="{% url 'page:create' %}">글쓰기</a>
    </span>
    <span>
      <a href="{% url 'game:rsp' %}">가위바위보 게임</a>
    </span>
    <span>
      <a href="{% url 'game:list_weapon' %}">무기 목록</a>
    </span>
    <span>
      <a href="{% url 'game:create_weapon' %}">무기 생성</a>
    </span>
  </div>

  <div class="container">
    {% block body %}
    {% endblock %}
  </div>
</body>
</html>

page/templates/page/create.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'css/page/create.css' %}">
{% endblock %}

{% block body %}
  <h1>글쓰기</h1>
  
  <!-- [미션] form의 전달방식을 post로 설정하기 -->
  <form action="" method="post">
    <!-- [미션] csrf_token 설정하기 -->
    {% csrf_token %}
    <table>
      <tr>
        <td><label for="title">제목</label></td>
        <!-- [미션] 서버에 딕셔너리 형식으로 전달되는 값의 Key값을 'title'로 설정하기 -->
        <td><input class="title" name="title" id="title" type="text" maxlength=50></td>
      </tr>
    </table>
    
    <br>

    <table>
      <tr>
        <td colspan="2">
          <label for="content">내용</label>
        </td>
      </tr>
      <tr>
        <td colspan="2">
          <!-- [미션] 서버에 딕셔너리 형식으로 전달되는 값의 Key값을 'content'로 설정하기 -->
          <textarea name="content" id="content" cols="30" rows="10"></textarea>
        </td>
      </tr>
    </table>

    <div class="right">
      <input class="button" type="submit" value="등록">
    </div>
  </form>
{% endblock %}

page/templates/page/detail.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'css/page/detail.css' %}">
{% endblock %}

{% block body %}
  <h1>작성 글 보기</h1>

  <table>
    <tr>
      <td class="title">{{posting.title}}</td>
      <td class="functions">
        <div class="right">
          <a class="button" href="{% url 'page:update' posting.id %}">수정</a>
          <a class="button" href="{% url 'page:delete' posting.id %}">삭제</a>
        </div>
      </td>
    </tr>
    <tr>
      <!-- [미션] 날짜를 보여주는 형식을 'Y-m-d A f'로 지정하기 -->
      <td colspan="2">작성일 : {{posting.date|date:'Y-m-d A f'}}</td>
    </tr>
    <tr>
      <td colspan="2">
        <div class="content">
          {{posting.content}}
        </div>
      </td>
    </tr>
  </table>

  <div class="right">
    <a class="button" href="{% url 'page:read' %}">글 목록</a>
  </div>
{% endblock %}

page/templates/page/index.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'css/page/index.css' %}">
{% endblock %}

{% block body %}
  <h1>메인 페이지</h1>
  
  <p>오늘의 목표</p>
  <ol>
    <li>Django의 CRUD에 대해 알아봅시다.</li>
    <li>DB에 저장된 데이터를 수정하고 삭제해봅시다.</li>
    <li>Django의 관리자 페이지에 대해 알아봅시다.</li>
  </ol>

  <img src="{% static 'images/walnut.jpg' %}" alt="walnut">
{% endblock %}

page/templates/page/read.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'css/page/read.css' %}">
{% endblock %}

{% block body %}
  <h1>작성 글 목록</h1>

  <div class="right">
    <a class="button" href="{% url 'page:create' %}">글쓰기</a>
  </div>

  <table>
    <tr>
      <th class="index">번호</th>
      <th class="title">제목</th>
      <th class="date">날짜</th>
    </tr>
    <!-- [미션] reversed를 이용해 for문을 거꾸로 반복하기 -->
    {% for posting in postings reversed %}
      <tr>
        <!-- [미션] forloop.revcounter를 이용하여 반복문의 index를 거꾸로 보여주기 -->
        <td class="index">{{forloop.revcounter}}</td>
        <td class="title"><a href="{% url 'page:detail' posting.id %}">{{posting.title}}</a></td>
        <!-- 날짜를 보여주는 형식을 'Y-m-d'로 지정하기 -->
        <td class="date">{{posting.date|date:'Y-m-d'}}</td>
      </tr>
    <!-- for문의 리스트가 비어있을 경우에 보여주는 내용 -->
    {% empty %}
      <tr>
        <td class="index">-</td>
        <td class="title">글을 작성해주세요.</td>
        <td class="date">-</td>
      </tr>
    {% endfor %}
  </table>
{% endblock %}

page/templates/page/update.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'css/page/update.css' %}">
{% endblock %}

{% block body %}
  <h1>글수정</h1>

  <!-- form의 전달방식을 post로 설정하기 -->
  <form action="" method="post">
    <!-- csrf_token 설정하기 -->
    {% csrf_token %}
    <table>
      <tr>
        <td><label for="title">제목</label></td>
        <!-- [코드 추가] 수정하기 전 title에 저장된 내용이 input 태그에 들어있도록 만들기 -->
        <td><input class="title" name="title" id="title" type="text" maxlength=50 value="{{posting.title}}"></td>
      </tr>
    </table>
    
    <br>

    <table>
      <tr>
        <td colspan="2">
          <label for="content">내용</label>
        </td>
      </tr>
      <tr>
        <td colspan="2">
          <!-- [코드 추가] 수정하기 전 content에 저장된 내용이 textarea 태그에 들어있도록 만들기 -->
          <textarea name="content" id="content" cols="30" rows="10">{{posting.content}}</textarea>
        </td>
      </tr>
    </table>

    <div class="right">
      <input class="button" type="submit" value="등록">
    </div>
  </form>
{% endblock %}